site_name: DeGov.AI Docs
site_url: https://degov.ai
site_description: "DeGov.AI is a governance platform that leverages AI to enhance decision-making and community engagement."
copyright: Copyright &copy; RingDAO 2025
repo_name: ringecosystem/degov-docs
edit_uri: https://github.com/ringecosystem/degov-docs/edit/main/docs
theme:
  name: material
  logo: resource/pics/degov.svg
  favicon: resource/pics/degov.svg
  font:
    text: San Francisco
    code: SFMono-Regular
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
 
extra:
  generator: false
  homepage: https://degov.ai
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringecosystem/degov
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ai_degov
    - icon: fontawesome/brands/telegram
      link: https://t.me/DeGov_AI

  analytics:
    provider: google
    property: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/ringecosystem/degov-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - resource/stylesheets/extra.css

plugins:
  - search
  - meta-descriptions:
      enable_checks: true
      max_length: 500
      trim: true
  - git-authors
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true
  - redirects:
      redirect_maps:

nav:
  - Home: 
      - What is DeGov.AI?: index.md
      - FAQs: faqs.md
  - Governance:
      - Introduction:
        - What are DAOs?: governance/intro/daos.md
        - Onchain Governance: governance/intro/onchain.md
        - Offchain Governance: governance/intro/offchain.md
        - Governance Model: governance/intro/model.md
      - Proposal: 
        - Overview: governance/proposal/overview.md
        - Lifecycle: governance/proposal/lifecycle.md
        - Voting: governance/proposal/voting.md
      - Delegation:
        - Overview: governance/delegation/overview.md

      - Key Parameters:
        - Proposal thresholds: governance/parameters/proposal-thresholds.md
        - Quorum: governance/parameters/quorum.md
        - Proposal delay: governance/parameters/proposal-delay.md
        - Voting period: governance/parameters/voting-period.md
        - TimeLock delay: governance/parameters/timelock-delay.md