name: Deploy staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Build mkdocs
        run: |
          pip install -r requirements.txt
          mkdocs build

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy to Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: degov-docs
          dist_path: site
          script_run: false
          enable_notify_slack: false
          slack_channel: public-degov
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}


